import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ShieldAlert, CheckCircle, AlertTriangle, Lock, Siren } from "lucide-react";
import { Button } from "@/components/ui/button";

const DISCLAIMER_KEY = "dentascan-disclaimer-accepted";

interface MedicalDisclaimerProps {
  onAccept: () => void;
}

const MedicalDisclaimer = ({ onAccept }: MedicalDisclaimerProps) => {
  const [countdown, setCountdown] = useState(5);
  const canAccept = countdown <= 0;

  useEffect(() => {
    if (countdown <= 0) return;
    const timer = setTimeout(() => setCountdown((c) => c - 1), 1000);
    return () => clearTimeout(timer);
  }, [countdown]);

  const handleAccept = () => {
    localStorage.setItem(DISCLAIMER_KEY, "true");
    onAccept();
  };

  return (
    <div className="fixed inset-0 z-[100] bg-background/95 backdrop-blur-sm flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-md bg-card border border-border rounded-2xl shadow-elevated overflow-hidden"
      >
        {/* Header Banner */}
        <div className="bg-urgency-red/10 border-b border-urgency-red/20 px-6 py-4 text-center">
          <div className="w-14 h-14 rounded-2xl bg-urgency-amber/10 flex items-center justify-center mx-auto mb-3">
            <ShieldAlert className="w-7 h-7 text-urgency-amber" />
          </div>
          <h2 className="font-heading font-bold text-lg text-foreground">IMPORTANT: MEDICAL DISCLAIMER</h2>
          <p className="text-xs font-semibold text-urgency-red mt-1">DentaScan AI is a Triage Assistant, NOT a Dentist.</p>
        </div>

        {/* Content */}
        <div className="px-6 py-5 space-y-4 max-h-[50vh] overflow-y-auto">
          {/* Point 1 */}
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-clinical-blue/10 flex items-center justify-center flex-shrink-0 mt-0.5">
              <ShieldAlert className="w-4 h-4 text-clinical-blue" />
            </div>
            <div>
              <h3 className="text-xs font-semibold text-foreground">Initial Assessment Only</h3>
              <p className="text-[11px] text-muted-foreground leading-relaxed mt-0.5">
                The plaque heatmaps, lesion tracking, and "Monster Hunter" zones are generated by AI algorithms for 
                <strong className="text-foreground"> educational and triage purposes only</strong>.
              </p>
            </div>
          </div>

          {/* Point 2 */}
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-urgency-amber/10 flex items-center justify-center flex-shrink-0 mt-0.5">
              <AlertTriangle className="w-4 h-4 text-urgency-amber" />
            </div>
            <div>
              <h3 className="text-xs font-semibold text-foreground">Clinical Verification Required</h3>
              <p className="text-[11px] text-muted-foreground leading-relaxed mt-0.5">
                AI findings are <strong className="text-foreground">estimates</strong>. All results must be confirmed by a 
                licensed Dental Professional using clinical instruments. 
                <strong className="text-foreground"> False negatives are possible</strong> — a "healthy" result does not 
                guarantee absence of pathology.
              </p>
            </div>
          </div>

          {/* Point 3 - Emergency */}
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-urgency-red/10 flex items-center justify-center flex-shrink-0 mt-0.5">
              <Siren className="w-4 h-4 text-urgency-red" />
            </div>
            <div>
              <h3 className="text-xs font-semibold text-urgency-red">Not an Emergency Service</h3>
              <p className="text-[11px] text-muted-foreground leading-relaxed mt-0.5">
                If you are experiencing <strong className="text-foreground">severe pain, swelling, or bleeding</strong>, 
                do not wait for an AI scan. <strong className="text-urgency-red">Seek immediate in-person emergency dental care.</strong>
              </p>
            </div>
          </div>

          {/* Point 4 */}
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-scan-green/10 flex items-center justify-center flex-shrink-0 mt-0.5">
              <Lock className="w-4 h-4 text-scan-green" />
            </div>
            <div>
              <h3 className="text-xs font-semibold text-foreground">Data Privacy</h3>
              <p className="text-[11px] text-muted-foreground leading-relaxed mt-0.5">
                Your dental scans are <strong className="text-foreground">encrypted (AES-256)</strong>. By clicking 'Accept,' 
                you agree to our HIPAA-compliant data processing terms and our 5-point Patient Privacy Promise.
              </p>
            </div>
          </div>

          {/* Privacy Promise */}
          <div className="rounded-xl bg-muted/30 border border-border p-3 space-y-1.5">
            <p className="text-[10px] font-semibold text-foreground uppercase tracking-wider">🛡️ Patient Privacy Promise</p>
            <ol className="text-[10px] text-muted-foreground space-y-1 pl-4 list-decimal">
              <li>Your scans are encrypted end-to-end and never sold to third parties.</li>
              <li>Only you and your chosen dental professional can access your data.</li>
              <li>All data is stored in HIPAA-compliant infrastructure with AES-256 encryption.</li>
              <li>You can request complete data deletion at any time.</li>
              <li>AI models do not retain your images after analysis is complete.</li>
            </ol>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6 pt-2 space-y-3">
          <Button
            variant="clinical"
            className="w-full haptic-button gap-2 h-12 text-sm"
            disabled={!canAccept}
            onClick={handleAccept}
          >
            {canAccept ? (
              <>
                <CheckCircle className="w-4 h-4" />
                I Accept & Start Scan
              </>
            ) : (
              `Please read carefully (${countdown}s)`
            )}
          </Button>

          <p className="text-[9px] text-center text-muted-foreground">
            You must accept this disclaimer to use DentaScan AI
          </p>
        </div>
      </motion.div>
    </div>
  );
};

export { DISCLAIMER_KEY };
export default MedicalDisclaimer;
